name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.4
        ports: ["5432:5432/tcp"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres

    steps:
    - run: sudo apt update && sudo apt install libpq-dev
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        pip install --upgrade pip poetry
        POETRY_VIRTUALENVS_IN_PROJECT=true poetry install
        echo ".venv/bin" >> $GITHUB_PATH

    - name: Test
      run: forge test
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
        DEBUG: true
        SECRET_KEY: testing
        BASE_URL: http://example.com
